### PR TITLE
support CPU for inference_images.py

### PR DESCRIPTION
**Pull request by jinzishuai**

### CODE REVIEW

**Comment by PeterL1n** [comment]
Thanks for your contribution. 

Are you able to modify it so that num_workers is not hardcoded in the file? Make it a command line argument `--num-workers` after line 56. Set its default to 0, but allow people to change it.

If you don't have time, I will make the change myself later.

**Comment by jinzishuai** [comment]
sure, I would be happy to do that for all 3 inteference codes.

**Comment by jinzishuai** [comment]
> Thanks for your contribution.
> 
> Are you able to modify it so that num_workers is not hardcoded in the file? Make it a command line argument `--num-workers` after line 56. Set its default to 0, but allow people to change it.
> 
> If you don't have time, I will make the change myself later.

@PeterL1n  this is the PR https://github.com/PeterL1n/BackgroundMattingV2/pull/28. please review. thanks.

**Comment by PeterL1n** [comment]
Merged the other pull request. I am closing this one.

**Pull request closed without merging**
